# Jupyter with PostgreSQL

In [ ]:
import sys
print(sys.version)

:

## Libararies and Settings

In [ ]:
# Libraries
import os
import psycopg2
import pandas as pd
from sqlalchemy import create_engine
import matplotlib.pyplot as plt

# Settings
import warnings
warnings.filterwarnings("ignore")

# Current working directory
print(os.getcwd())

:

## Create database connection

In [51]:
import psycopg2

# Verbinden mit der PostgreSQL-Datenbank im Docker-Container über den lokalen Port 5432
conn = psycopg2.connect(
    host="localhost",
    dbname="app",
    user="app_user",
    password="app_password",
    port=5432
)

In [50]:
conn = psycopg2.connect("host=localhost dbname=app user=app_user password=app_password")

In [44]:
conn = psycopg2.connect("host=localhost dbname=postgres user=app_user password=app_password")

## Read data

In [52]:
df = pd.read_csv('apartments_data_prepared.csv', sep=',')
df.head(5)

,web-scraper-order,web-scraper-start-url,rooms_area_price_raw,address_raw,price_raw,description_raw,text_raw,rooms,area,price
0,1662023695-433,https://www.immoscout24.ch/de/wohnung/mieten/k...,"3,5 Zimmer, 122 m², CHF 3180.—","Sunnenbergstrasse 15, 8633 Wolfhausen, ZH",CHF 3180.—,"«Grosse Galerie, Terrasse mit Pergola, Berg- u...","3,5 Zimmer, 122 m², CHF 3180.—Sunnenbergstrass...",3.5,122.0,3180.0
1,1662023745-820,https://www.immoscout24.ch/de/wohnung/mieten/k...,"2,5 Zimmer, 78 m², CHF 3760.—","Lavaterstr. 63, 8002 Zürich, ZH",CHF 3760.—,«Wunderschöne Wohnung im Enge-Quartier»,"2,5 Zimmer, 78 m², CHF 3760.—Lavaterstr. 63, 8...",2.5,78.0,3760.0
2,1662023742-807,https://www.immoscout24.ch/de/wohnung/mieten/k...,"5,5 Zimmer, 115 m², CHF 2860.—","Langfurrenstrasse 5c, 8623 Wetzikon ZH, ZH",CHF 2860.—,«Wohnmomente zum Festhalten»,"5,5 Zimmer, 115 m², CHF 2860.—Langfurrenstrass...",5.5,115.0,2860.0
3,1662023804-1290,https://www.immoscout24.ch/de/wohnung/mieten/k...,"3,5 Zimmer, 74 m², CHF 2165.—","Sandbuckweg 5A, 8157 Dielsdorf, ZH",CHF 2165.—,"«3,5 pièces, 74 m²»","top3,5 Zimmer, 74 m², CHF 2165.—Sandbuckweg 5A...",3.5,74.0,2165.0
4,1662023739-771,https://www.immoscout24.ch/de/wohnung/mieten/k...,"5,5 Zimmer, 195 m², CHF 6900.—","Parkring 59, 8002 Zürich, ZH",CHF 6900.—,«Wohnanlage Im Parkring - Exklusive Wohnung zu...,"5,5 Zimmer, 195 m², CHF 6900.—Parkring 59, 800...",5.5,195.0,6900.0

## Write data to database

In [54]:
engine = create_engine('postgresql://app_user:app_password@localhost:5432/app')
df.to_sql('apartment_table', engine, if_exists='replace')

8

## Make SQL query

In [58]:
df_sub = pd.read_sql_query('''SELECT
                             address_raw,
                             rooms,
                             area,
                             price
                             FROM apartment_table''', 
                          con=engine)
df_sub.head()

                                  address_raw  rooms   area   price
0   Sunnenbergstrasse 15, 8633 Wolfhausen, ZH    3.5  122.0  3180.0
1             Lavaterstr. 63, 8002 Zürich, ZH    2.5   78.0  3760.0
2  Langfurrenstrasse 5c, 8623 Wetzikon ZH, ZH    5.5  115.0  2860.0
3          Sandbuckweg 5A, 8157 Dielsdorf, ZH    3.5   74.0  2165.0
4                Parkring 59, 8002 Zürich, ZH    5.5  195.0  6900.0

## Plot apartment prices

In [56]:
# Plot Histogram
fig = plt.figure( figsize=(7,4))
plt.xticks(fontsize=14, rotation=0)
plt.yticks(fontsize=14, rotation=0)
n, bins, patches = plt.hist(x=df['price'], 
                            bins=20, 
                            color='#5DADE2',
                            alpha=1.00, 
                            rwidth=0.95
                   )
plt.grid(True)
plt.ticklabel_format(style='plain')
plt.grid(axis='y', alpha=0.75)

# Set labels
plt.xlabel('price', fontsize=10, labelpad=10)
plt.ylabel('Frequency', fontsize=10, labelpad=10)
plt.title('Histogram of apartment prices', fontsize=12, pad=10)

# Set fontsize of tick labels
plt.xticks(fontsize = 10)
plt.yticks(fontsize = 10)

plt.show()

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/vscode/.local/lib/python3.10/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/home/vscode/.local/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 728, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/vscode/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 513, in dispatch_queue
    await self.process_one()
  File "/home/vscode/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 502, in process_one
    await dispatch(*args)
  File "/home/vscode/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 409, in dispatch_shell
    await result
  File "/home/vscode/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 729, in execute_request
    reply_content = await reply_content
  File "/home/vscode/.local/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 423, in do_execute
    res = shell.run_cell(
  File "/home/vscode/.local/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 540, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3006, in run_cell
    result = self._run_cell(
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3061, in _run_cell
    result = runner(coro)
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3266, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3445, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_4664/1721368517.py", line 2, in <module>
    fig = plt.figure( figsize=(7,4))
  File "/home/vscode/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1027, in figure
  File "/home/vscode/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 549, in new_figure_manager
    `~contextlib.ExitStack` object, which is not intended to be stored or
  File "/home/vscode/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 526, in _warn_if_gui_out_of_main_thread
    --------
  File "/home/vscode/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 358, in _get_backend_mod
  File "/home/vscode/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 415, in switch_backend
    that the event loop is running to have responsive figures.
  File "/home/vscode/.local/lib/python3.10/site-packages/matplotlib/backends/registry.py", line 323, in load_backend_module
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib_inline/__init__.py", line 1, in <module>
    from . import backend_inline, config  # noqa
  File "/usr/local/lib/python3.10/dist-packages/matplotlib_inline/backend_inline.py", line 8, in <module>
    from matplotlib.backends import backend_agg
  File "/home/vscode/.local/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 40, in <module>
    from matplotlib.backends._backend_agg import RendererAgg as _RendererAgg

AttributeError: _ARRAY_API not found

Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_4664/1721368517.py", line 2, in <module>
    fig = plt.figure( figsize=(7,4))
  File "/home/vscode/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1027, in figure
  File "/home/vscode/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 549, in new_figure_manager
    `~contextlib.ExitStack` object, which is not intended to be stored or
  File "/home/vscode/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 526, in _warn_if_gui_out_of_main_thread
    --------
  File "/home/vscode/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 358, in _get_backend_mod
  File "/home/vscode/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 415, in switch_backend
    that the event loop is running to have responsive figures.
  File "/home/vscode/.local/lib/python3.10/site-packages/matplotlib/backends/registry.py", line 323, in load_backend_module
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/matplotlib_inline/__init__.py", line 1, in <module>
    from . import backend_inline, config  # noqa
  File "/usr/local/lib/python3.10/dist-packages/matplotlib_inline/backend_inline.py", line 8, in <module>
    from matplotlib.backends import backend_agg
  File "/home/vscode/.local/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 40, in <module>
    from matplotlib.backends._backend_agg import RendererAgg as _RendererAgg
ImportError: numpy.core.multiarray failed to import

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2102, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1310, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1199, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1052, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 978, in format_exception_as_a_whole
    frames.append(self.format_record(record))
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 878, in format_record
    frame_info.lines, Colors, self.has_colors, lvals
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 712, in lines
    return self._sd.lines
  File "/usr/local/lib/python3.10/dist-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.10/dist-packages/stack_data/core.py", line 734, in lines
    pieces = self.included_pieces
  File "/usr/local/lib/python3.10/dist-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.10/dist-packages/stack_data/core.py", line 681, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "/usr/local/lib/python3.10/dist-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.10/dist-packages/stack_data/core.py", line 660, in executing_piece
    return only(
  File "/usr/local/lib/python3.10/dist-packages/executing/executing.py", line 116, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0

### Jupyter notebook --footer info-- (please always provide this at the end of each notebook)

In [57]:
import os
import platform
import socket
from platform import python_version
from datetime import datetime

print('-----------------------------------')
print(os.name.upper())
print(platform.system(), '|', platform.release())
print('Datetime:', datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print('Python Version:', python_version())
print('-----------------------------------')

-----------------------------------
POSIX
Linux | 6.10.4-linuxkit
Datetime: 2024-11-01 09:20:32
Python Version: 3.10.12
-----------------------------------